### ISSUE TITLE
gretty doesn't work with spring boot 2.0.0

### ISSUE THREAD

**Issue by rssdev10** [akhikhl/gretty#407]
There are at least two issues. 

SpringBootMainClassFinder doesn't separate renamed property mainClassName. When I tried to run the app by gradle runApp I got 

```
Could not get unknown property 'mainClass' for object of type org.springframework.boot.gradle.dsl.SpringBootExtension.
```

Actually I already fixed it in https://github.com/rssdev10/gretty/commit/583b2304d4a0d49e621648bc28253e5dda9788d0

But second issue is:

```
 Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/DefaultParser
         at groovy.util.CliBuilder.parse(CliBuilder.groovy:356)
         at groovy.util.CliBuilder$parse$1.call(Unknown Source)
         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
         at org.akhikhl.gretty.Runner.main(Runner.groovy:44)
 Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.DefaultParser
         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```
I checked the project gretty-runner. It contains compile 'commons-cli:commons-cli:1.2'. I tried to debug the  org.akhikhl.gretty.Runner.main but not able to see in an interactive debugger what is happening inside the method CliBuilder.parse. Any ideas how to fix it?

See the attached example of spring boot 2 app.
[demo-spring-boot-2.zip](https://github.com/akhikhl/gretty/files/1468271/demo-spring-boot-2.zip)

**Comment by henrik242** [comment]
Try replacing with the `commons-cli:commons-cli:1.3.1` dependency, maybe that helps?

**Comment by henrik242** [comment]
@rssdev10 Did you solve this?

**Comment by tiemei** [comment]
same problem. 

gretty 2.2.0 
spring boot 2.0.2.RELEASE

**Comment by chuntungho** [comment]
looking forward to the solution

**Comment by tedpoovey** [comment]
Also ran into this issue.

Exception in thread "main" java.lang.NoClassDefFoundError: groovy/util/CliBuilder
	at org.akhikhl.gretty.Runner.main(Runner.groovy:40)
Caused by: java.lang.ClassNotFoundException: groovy.util.CliBuilder

Using current     dependencies {
        classpath "gradle.plugin.org.gretty:gretty:2.3.1"

**Comment by janacm** [comment]
Updating gretty helped:

id 'org.gretty' version '3.0.1'
